### ISSUE TITLE
repo down/deb unavailable

### ISSUE THREAD

**Issue by git-anish** [arandomdev/FastAuthentication#2]
hey, I used to have a backup of this deb

could you please upload it here or get your repo back up?

**Comment by arandomdev** [comment]
weird, make sure you're using this repo https://arandomdev.github.io/repo/

but if that doesn't work, here is a like to the latest version. https://arandomdev.github.io/repo/debians/com.haotestlabs.fastauthentication_1.0.0-1_iphoneos-arm.deb

**Comment by git-anish** [comment]
ah thanks, is this unsupported for iOS 14?

**Comment by arandomdev** [comment]
You can try it, but it’s a very old project
